### ISSUE TITLE
Series slug change

### ISSUE THREAD

**Issue by Vedantpr0** [PrabhuKiran8790/prabhukirankonda.vercel.app#14]
Can we change spn order slug in path.
For example /blog/series-spn1-seriespost
To /blog/seriepost

I don't do webd so can it be possible if yes can you share some references I will try to implement it.
Or can I use headless like hashnode same layout.

**Comment by PrabhuKiran8790** [comment]
You can, but in case if you accidentally give same name to the subposts in the series (or in some other series), the link breaks. You can refer to `getSeriesPosts` function in `posts.ts`.

**Comment by Vedantpr0** [comment]
bro tried 

slug: `${coverFolder}/${blog.split('/')[3].split('.')[0]}`
										
 and at  routes/blog/+pages.ts
 `const pattern: RegExp = /\//; // -spn{order}- is the pattern for series post
`
I am still getting error can you help it out bit
@PrabhuKiran8790
