### ISSUE TITLE
ending your repo on .app may not be the best idea

### ISSUE THREAD

**Issue by Antoine-lb** [PrabhuKiran8790/prabhukirankonda.vercel.app#3]
Hello, nice blog

I cloned it on my mac and got:
<img width="167" alt="SCR-20231130-pkqi" src="https://github.com/PrabhuKiran8790/prabhukirankonda.vercel.app/assets/27826950/d18b0fe5-0197-44c2-b5d0-70077827dd89">

That is because it ends on .app, which is a extention on macos, so it behaves like a broken app.

It can be renamed on the cloning phase, so it's no a big deal

**Comment by PrabhuKiran8790** [comment]
Oops! I never thought of this even though I'm using a mac. I feel dumb. I'll change it,  Thank you.
